# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/PTH/Web_Blog

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/PTH/Web_Blog

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/PTH/Web_Blog/CMakeFiles /home/ubuntu/PTH/Web_Blog/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/PTH/Web_Blog/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run.exe

# Build rule for target.
run.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 run.exe
.PHONY : run.exe

# fast build rule for target.
run.exe/fast:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/build
.PHONY : run.exe/fast

source-code/buffer/buffer.o: source-code/buffer/buffer.cpp.o

.PHONY : source-code/buffer/buffer.o

# target to build an object file
source-code/buffer/buffer.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/buffer/buffer.cpp.o
.PHONY : source-code/buffer/buffer.cpp.o

source-code/buffer/buffer.i: source-code/buffer/buffer.cpp.i

.PHONY : source-code/buffer/buffer.i

# target to preprocess a source file
source-code/buffer/buffer.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/buffer/buffer.cpp.i
.PHONY : source-code/buffer/buffer.cpp.i

source-code/buffer/buffer.s: source-code/buffer/buffer.cpp.s

.PHONY : source-code/buffer/buffer.s

# target to generate assembly for a file
source-code/buffer/buffer.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/buffer/buffer.cpp.s
.PHONY : source-code/buffer/buffer.cpp.s

source-code/cookie/cookie.o: source-code/cookie/cookie.cpp.o

.PHONY : source-code/cookie/cookie.o

# target to build an object file
source-code/cookie/cookie.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/cookie/cookie.cpp.o
.PHONY : source-code/cookie/cookie.cpp.o

source-code/cookie/cookie.i: source-code/cookie/cookie.cpp.i

.PHONY : source-code/cookie/cookie.i

# target to preprocess a source file
source-code/cookie/cookie.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/cookie/cookie.cpp.i
.PHONY : source-code/cookie/cookie.cpp.i

source-code/cookie/cookie.s: source-code/cookie/cookie.cpp.s

.PHONY : source-code/cookie/cookie.s

# target to generate assembly for a file
source-code/cookie/cookie.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/cookie/cookie.cpp.s
.PHONY : source-code/cookie/cookie.cpp.s

source-code/epoller/epoller.o: source-code/epoller/epoller.cpp.o

.PHONY : source-code/epoller/epoller.o

# target to build an object file
source-code/epoller/epoller.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/epoller/epoller.cpp.o
.PHONY : source-code/epoller/epoller.cpp.o

source-code/epoller/epoller.i: source-code/epoller/epoller.cpp.i

.PHONY : source-code/epoller/epoller.i

# target to preprocess a source file
source-code/epoller/epoller.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/epoller/epoller.cpp.i
.PHONY : source-code/epoller/epoller.cpp.i

source-code/epoller/epoller.s: source-code/epoller/epoller.cpp.s

.PHONY : source-code/epoller/epoller.s

# target to generate assembly for a file
source-code/epoller/epoller.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/epoller/epoller.cpp.s
.PHONY : source-code/epoller/epoller.cpp.s

source-code/http/httpconn.o: source-code/http/httpconn.cpp.o

.PHONY : source-code/http/httpconn.o

# target to build an object file
source-code/http/httpconn.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httpconn.cpp.o
.PHONY : source-code/http/httpconn.cpp.o

source-code/http/httpconn.i: source-code/http/httpconn.cpp.i

.PHONY : source-code/http/httpconn.i

# target to preprocess a source file
source-code/http/httpconn.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httpconn.cpp.i
.PHONY : source-code/http/httpconn.cpp.i

source-code/http/httpconn.s: source-code/http/httpconn.cpp.s

.PHONY : source-code/http/httpconn.s

# target to generate assembly for a file
source-code/http/httpconn.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httpconn.cpp.s
.PHONY : source-code/http/httpconn.cpp.s

source-code/http/httprequest.o: source-code/http/httprequest.cpp.o

.PHONY : source-code/http/httprequest.o

# target to build an object file
source-code/http/httprequest.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httprequest.cpp.o
.PHONY : source-code/http/httprequest.cpp.o

source-code/http/httprequest.i: source-code/http/httprequest.cpp.i

.PHONY : source-code/http/httprequest.i

# target to preprocess a source file
source-code/http/httprequest.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httprequest.cpp.i
.PHONY : source-code/http/httprequest.cpp.i

source-code/http/httprequest.s: source-code/http/httprequest.cpp.s

.PHONY : source-code/http/httprequest.s

# target to generate assembly for a file
source-code/http/httprequest.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httprequest.cpp.s
.PHONY : source-code/http/httprequest.cpp.s

source-code/http/httpresponse.o: source-code/http/httpresponse.cpp.o

.PHONY : source-code/http/httpresponse.o

# target to build an object file
source-code/http/httpresponse.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httpresponse.cpp.o
.PHONY : source-code/http/httpresponse.cpp.o

source-code/http/httpresponse.i: source-code/http/httpresponse.cpp.i

.PHONY : source-code/http/httpresponse.i

# target to preprocess a source file
source-code/http/httpresponse.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httpresponse.cpp.i
.PHONY : source-code/http/httpresponse.cpp.i

source-code/http/httpresponse.s: source-code/http/httpresponse.cpp.s

.PHONY : source-code/http/httpresponse.s

# target to generate assembly for a file
source-code/http/httpresponse.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/http/httpresponse.cpp.s
.PHONY : source-code/http/httpresponse.cpp.s

source-code/log/log.o: source-code/log/log.cpp.o

.PHONY : source-code/log/log.o

# target to build an object file
source-code/log/log.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/log/log.cpp.o
.PHONY : source-code/log/log.cpp.o

source-code/log/log.i: source-code/log/log.cpp.i

.PHONY : source-code/log/log.i

# target to preprocess a source file
source-code/log/log.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/log/log.cpp.i
.PHONY : source-code/log/log.cpp.i

source-code/log/log.s: source-code/log/log.cpp.s

.PHONY : source-code/log/log.s

# target to generate assembly for a file
source-code/log/log.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/log/log.cpp.s
.PHONY : source-code/log/log.cpp.s

source-code/main.o: source-code/main.cpp.o

.PHONY : source-code/main.o

# target to build an object file
source-code/main.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/main.cpp.o
.PHONY : source-code/main.cpp.o

source-code/main.i: source-code/main.cpp.i

.PHONY : source-code/main.i

# target to preprocess a source file
source-code/main.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/main.cpp.i
.PHONY : source-code/main.cpp.i

source-code/main.s: source-code/main.cpp.s

.PHONY : source-code/main.s

# target to generate assembly for a file
source-code/main.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/main.cpp.s
.PHONY : source-code/main.cpp.s

source-code/redisconnpool/redisconnpool.o: source-code/redisconnpool/redisconnpool.cpp.o

.PHONY : source-code/redisconnpool/redisconnpool.o

# target to build an object file
source-code/redisconnpool/redisconnpool.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/redisconnpool/redisconnpool.cpp.o
.PHONY : source-code/redisconnpool/redisconnpool.cpp.o

source-code/redisconnpool/redisconnpool.i: source-code/redisconnpool/redisconnpool.cpp.i

.PHONY : source-code/redisconnpool/redisconnpool.i

# target to preprocess a source file
source-code/redisconnpool/redisconnpool.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/redisconnpool/redisconnpool.cpp.i
.PHONY : source-code/redisconnpool/redisconnpool.cpp.i

source-code/redisconnpool/redisconnpool.s: source-code/redisconnpool/redisconnpool.cpp.s

.PHONY : source-code/redisconnpool/redisconnpool.s

# target to generate assembly for a file
source-code/redisconnpool/redisconnpool.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/redisconnpool/redisconnpool.cpp.s
.PHONY : source-code/redisconnpool/redisconnpool.cpp.s

source-code/server/server.o: source-code/server/server.cpp.o

.PHONY : source-code/server/server.o

# target to build an object file
source-code/server/server.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/server/server.cpp.o
.PHONY : source-code/server/server.cpp.o

source-code/server/server.i: source-code/server/server.cpp.i

.PHONY : source-code/server/server.i

# target to preprocess a source file
source-code/server/server.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/server/server.cpp.i
.PHONY : source-code/server/server.cpp.i

source-code/server/server.s: source-code/server/server.cpp.s

.PHONY : source-code/server/server.s

# target to generate assembly for a file
source-code/server/server.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/server/server.cpp.s
.PHONY : source-code/server/server.cpp.s

source-code/sqlconnpool/sqlconnpool.o: source-code/sqlconnpool/sqlconnpool.cpp.o

.PHONY : source-code/sqlconnpool/sqlconnpool.o

# target to build an object file
source-code/sqlconnpool/sqlconnpool.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/sqlconnpool/sqlconnpool.cpp.o
.PHONY : source-code/sqlconnpool/sqlconnpool.cpp.o

source-code/sqlconnpool/sqlconnpool.i: source-code/sqlconnpool/sqlconnpool.cpp.i

.PHONY : source-code/sqlconnpool/sqlconnpool.i

# target to preprocess a source file
source-code/sqlconnpool/sqlconnpool.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/sqlconnpool/sqlconnpool.cpp.i
.PHONY : source-code/sqlconnpool/sqlconnpool.cpp.i

source-code/sqlconnpool/sqlconnpool.s: source-code/sqlconnpool/sqlconnpool.cpp.s

.PHONY : source-code/sqlconnpool/sqlconnpool.s

# target to generate assembly for a file
source-code/sqlconnpool/sqlconnpool.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/sqlconnpool/sqlconnpool.cpp.s
.PHONY : source-code/sqlconnpool/sqlconnpool.cpp.s

source-code/threadpool/threadpool.o: source-code/threadpool/threadpool.cpp.o

.PHONY : source-code/threadpool/threadpool.o

# target to build an object file
source-code/threadpool/threadpool.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/threadpool/threadpool.cpp.o
.PHONY : source-code/threadpool/threadpool.cpp.o

source-code/threadpool/threadpool.i: source-code/threadpool/threadpool.cpp.i

.PHONY : source-code/threadpool/threadpool.i

# target to preprocess a source file
source-code/threadpool/threadpool.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/threadpool/threadpool.cpp.i
.PHONY : source-code/threadpool/threadpool.cpp.i

source-code/threadpool/threadpool.s: source-code/threadpool/threadpool.cpp.s

.PHONY : source-code/threadpool/threadpool.s

# target to generate assembly for a file
source-code/threadpool/threadpool.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/threadpool/threadpool.cpp.s
.PHONY : source-code/threadpool/threadpool.cpp.s

source-code/timer/heaptimer.o: source-code/timer/heaptimer.cpp.o

.PHONY : source-code/timer/heaptimer.o

# target to build an object file
source-code/timer/heaptimer.cpp.o:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/timer/heaptimer.cpp.o
.PHONY : source-code/timer/heaptimer.cpp.o

source-code/timer/heaptimer.i: source-code/timer/heaptimer.cpp.i

.PHONY : source-code/timer/heaptimer.i

# target to preprocess a source file
source-code/timer/heaptimer.cpp.i:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/timer/heaptimer.cpp.i
.PHONY : source-code/timer/heaptimer.cpp.i

source-code/timer/heaptimer.s: source-code/timer/heaptimer.cpp.s

.PHONY : source-code/timer/heaptimer.s

# target to generate assembly for a file
source-code/timer/heaptimer.cpp.s:
	$(MAKE) -f CMakeFiles/run.exe.dir/build.make CMakeFiles/run.exe.dir/source-code/timer/heaptimer.cpp.s
.PHONY : source-code/timer/heaptimer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... run.exe"
	@echo "... source-code/buffer/buffer.o"
	@echo "... source-code/buffer/buffer.i"
	@echo "... source-code/buffer/buffer.s"
	@echo "... source-code/cookie/cookie.o"
	@echo "... source-code/cookie/cookie.i"
	@echo "... source-code/cookie/cookie.s"
	@echo "... source-code/epoller/epoller.o"
	@echo "... source-code/epoller/epoller.i"
	@echo "... source-code/epoller/epoller.s"
	@echo "... source-code/http/httpconn.o"
	@echo "... source-code/http/httpconn.i"
	@echo "... source-code/http/httpconn.s"
	@echo "... source-code/http/httprequest.o"
	@echo "... source-code/http/httprequest.i"
	@echo "... source-code/http/httprequest.s"
	@echo "... source-code/http/httpresponse.o"
	@echo "... source-code/http/httpresponse.i"
	@echo "... source-code/http/httpresponse.s"
	@echo "... source-code/log/log.o"
	@echo "... source-code/log/log.i"
	@echo "... source-code/log/log.s"
	@echo "... source-code/main.o"
	@echo "... source-code/main.i"
	@echo "... source-code/main.s"
	@echo "... source-code/redisconnpool/redisconnpool.o"
	@echo "... source-code/redisconnpool/redisconnpool.i"
	@echo "... source-code/redisconnpool/redisconnpool.s"
	@echo "... source-code/server/server.o"
	@echo "... source-code/server/server.i"
	@echo "... source-code/server/server.s"
	@echo "... source-code/sqlconnpool/sqlconnpool.o"
	@echo "... source-code/sqlconnpool/sqlconnpool.i"
	@echo "... source-code/sqlconnpool/sqlconnpool.s"
	@echo "... source-code/threadpool/threadpool.o"
	@echo "... source-code/threadpool/threadpool.i"
	@echo "... source-code/threadpool/threadpool.s"
	@echo "... source-code/timer/heaptimer.o"
	@echo "... source-code/timer/heaptimer.i"
	@echo "... source-code/timer/heaptimer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

